"""tabela pessoa2

Revision ID: 0be4a1d1c164
Revises: 21474ff6eb6a
Create Date: 2024-11-29 17:29:07.603561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0be4a1d1c164'
down_revision: Union[str, None] = '21474ff6eb6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
