"""adicionando coluna sexo

Revision ID: 9035b8f9fc06
Revises: 42ed960ad58f
Create Date: 2024-11-29 17:55:20.072373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9035b8f9fc06'
down_revision: Union[str, None] = '42ed960ad58f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pessoa', sa.Column('sexo', sa.String(length=1), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pessoa', 'sexo')
    # ### end Alembic commands ###
