"""adicionando coluna sexo em pessoa 2

Revision ID: f2406adf822f
Revises: 223416704ed1
Create Date: 2024-11-29 18:01:45.513315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2406adf822f'
down_revision: Union[str, None] = '223416704ed1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pessoa2', sa.Column('sexo', sa.String(length=1), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pessoa2', 'sexo')
    # ### end Alembic commands ###
